version: "3.3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./:/app:z
      - todd-data:/todd-data
    environment:
      TODD_JWT_KEY: OxBCcXjmBdXm37e9E3iIABuTdv1W9rUBID96ZZ3A0H3C6Iplf5
  db:
    image: "postgres:12.1"
    environment:
        POSTGRES_DB: todd_db
        POSTGRES_USER: todd
        POSTGRES_PASSWORD: todd
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-data/initdb.d:/docker-entrypoint-initdb.d/
volumes:
  postgres-data:
  todd-data: