version: "3.3"

services:
  web-prod:
    image: "jamerst/todd:latest"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
    volumes:
      - todd-data:/todd-data
      - /certs:/certs
    environment:
        ASPNETCORE_URLS: https://+;http://+
        ASPNETCORE_HTTPS_PORT: 443
        ASPNETCORE_Kestrel__Certificates__Default__Password: PASSWORD_HERE
        ASPNETCORE_Kestrel__Certificates__Default__Path: /certs/todd-https.pfx
        TODD_JWT_KEY: JWT_SECRET_KEY_HERE
        TODD_JWT_REFRESH_KEY: JWT_SECRET_KEY_HERE
    restart: always
  db:
    image: "postgres:12.1"
    environment:
        POSTGRES_DB: todd_db
        POSTGRES_USER: todd
        POSTGRES_PASSWORD: todd
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-data/initdb.d:/docker-entrypoint-initdb.d/
    restart: always
volumes:
  postgres-data:
  todd-data: